name: Mescoda's Blog

author: mescoda

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title

url: http://mescoda.com

navs:
    - title: Archive
      url: /archive
    - title: About
      url: /about
    - title: RSS
      url: /feed
